name: circ
description: "A new Flutter project."

publish_to: "none"

# version: 1.1.4+18
version: 1.2.0+22


environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^9.0.5
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
  hive_flutter: ^1.1.0
  go_router: ^17.0.0
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  skeletonizer: ^2.1.0+1
  flutter_svg: ^2.2.2
  shared_preferences: ^2.5.3
  loader_overlay: ^5.0.0
  provider: ^6.1.5+1
  badges: ^3.1.2
  carousel_slider: ^5.1.1
  dotted_border: ^3.1.0
  image_picker: ^1.2.1
  image_cropper: ^11.0.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  flutter_animate: ^4.5.2
  lottie: ^3.3.2
  video_thumbnail: ^0.5.6
  path_provider: ^2.1.5
  socket_io_client: ^3.1.2
  flutterwave_standard: ^1.1.0
  flutter_dotenv: ^6.0.0
  share_plus: ^12.0.1
  flutter_rating_bar: ^4.0.1
  firebase_messaging: ^16.0.4
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  flutter_local_notifications: ^19.5.0
  intl: ^0.20.2
  pay_with_paystack: ^1.0.14
  http: ^1.6.0
  date_picker_plus: ^4.2.0
  app_links: ^7.0.0
  shimmer: ^3.0.0
  flick_video_player: ^0.9.0
  pinput: ^6.0.0
  video_player: ^2.10.0
  flutter_html: ^3.0.0
  nigeria_states_dropdown: ^0.0.1
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1
  the_apple_sign_in: ^1.1.1
  jwt_decode: ^0.3.1
  device_info_plus: ^12.2.0
  flutter_sticky_header: ^0.8.0
  photo_view: ^0.15.0
  url_launcher: ^6.3.2
  external_app_launcher: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: ^2.4.15

  freezed: ^3.0.6

  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/
    - assets/svg/
    - assets/partners/
    - .env
    - assets/mock/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf

    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans/DMSans-Regular.ttf

    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf

    - family: LeagueSpartan
      fonts:
        - asset: assets/fonts/LeagueSpartan/LeagueSpartan-Regular.ttf

    - family: NeueMontreal
      fonts:
        - asset: assets/fonts/NeueMontreal/NeueMontreal-Regular.otf
        - asset: assets/fonts/NeueMontreal/NeueMontreal-Bold.otf
          weight: 700
        - asset: assets/fonts/NeueMontreal/NeueMontreal-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/NeueMontreal/NeueMontreal-Medium.otf
          weight: 500
        - asset: assets/fonts/NeueMontreal/NeueMontreal-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/NeueMontreal/NeueMontreal-Light.otf
          weight: 300
        - asset: assets/fonts/NeueMontreal/NeueMontreal-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/NeueMontreal/NeueMontreal-Italic.otf
          style: italic
